spring.application.name=mindu
spring.datasource.url=jdbc:postgresql://localhost:5432/mindu
spring.datasource.username=postgres
spring.datasource.password=admin

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=mindu-secret-key-must-be-at-least-256-bits-long-for-hs256
jwt.expiration=86400000
jwt.expiration=86400000

openai.api.key=${OPENAI_API_KEY:}
openai.model=llama-3.3-70b-versatile
openai.transcription.model=whisper-large-v3-turbo

openai.responses.url=https://api.groq.com/openai/v1/responses
openai.transcriptions.url=https://api.groq.com/openai/v1/audio/transcriptions