spring.application.name=mindu
spring.datasource.url=jdbc:postgresql://localhost:5432/mindu
spring.datasource.username=postgres
spring.datasource.password=root

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=mindu-secret-key-must-be-at-least-256-bits-long-for-hs256
jwt.expiration=86400000